<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>throw 예외 강제 발생</title>
    <script>
        function test() {
            try {
                alert('A 위치 입니다.')
                //오류의 여부와 관계없이 예외를 강제로 발생시킴
                throw "예외 강제 발생"  
            } catch (exception) {// exception은 예외객체의 주소를 가지고 있는 변수임 예외객제 그 자체가 아님
                alert('B 위치입니다.')
                return
            }
            alert('C위치입니다.')
        }
    </script>
     <script>
        function test() {
            try {
                alert('A 위치 입니다.')
                //오류의 여부와 관계없이 예외를 강제로 발생시킴
                throw "예외 강제 발생"  
            } catch (exception) {
                alert('B 위치입니다.')
                return
            } finally {
            alert('C위치입니다.')
        }
    }
    test()
    </script>
</head>
<body>
    
</body>
</html>